

- name: Add Docker Apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: install packages
  apt:
    package: "docker-ce={{ docker.engine.version }}~ce-0~ubuntu"
    state: present

- name: Create a docker group
  group:
    name: docker
    state: present

- name: Add the current user to the docker group
  user:
    name: "{{ user.name }}"
    groups: docker
    append: yes

- name: Docker daemon configuration
  template:
    src: docker/daemon.json
    owner: root
    group: root
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- name: start and configure Docker
  systemd:
    name: docker
    state: started

- name: start Docker on boot
  systemd:
    name: docker
    enabled: yes

- { include: get-and-cache.yml, toget: "https://github.com/docker/machine/releases/download/v{{ docker.machine.version }}/docker-machine-Linux-x86_64" }

- name: Install Docker Machine
  copy:
    src: "{{ cached }}"
    dest: /usr/local/bin/docker-machine

- name: Make Docker Machine executable
  file:
    path: /usr/local/bin/docker-machine
    state: file
    mode: "u+rx,a+x,g+x"

- { include: get-and-cache.yml, toget: "https://github.com/docker/compose/releases/download/{{ docker.compose.version }}/docker-compose-Linux-x86_64" }

- name: Install Docker Compose
  copy:
    src: "{{ cached }}"
    dest: /usr/local/bin/docker-compose

- name: Make Docker Machine compose
  file:
    path: /usr/local/bin/docker-compose
    state: file
    mode: "u+rx,a+x,g+x"
