
- name: Docker systemd configuration
  sudo: yes
  template: src=docker/docker.repo owner=root group=root dest=/etc/yum.repos.d/docker.repo

- name: install packages
  sudo: yes
  dnf: name=docker-engine-1.9.1 state=present

- name: Create a docker group
  sudo: yes
  group: name=docker state=present
  tags: fast

- name: Add the current user to the docker group
  sudo: yes
  user: name="{{ user.name }}" groups=docker append=yes
  tags: fast

- name: Docker systemd configuration
  sudo: yes
  template: src=docker/docker-systemd-config owner=root group=root dest=/usr/lib/systemd/system/docker.service
  notify:
   - restart docker
  tags: fast

- name: start and configure Docker
  service: name=docker state=started
  sudo: yes
  tags: fast

- name: start Docker on boot
  sudo: yes
  service: name=docker enabled=yes

- { include: get-and-cache.yml, toget: "https://github.com/docker/machine/releases/download/v0.5.0/docker-machine_linux-amd64" }

- name: Install Docker machine
  sudo: yes
  copy: src="{{ cached }}" dest=/usr/local/bin/docker-machine

- name: Make Docker Machine executable
  sudo: yes
  file: path=/usr/local/bin/docker-machine state=file mode="u+rx,a+x,g+x"

- { include: get-and-cache.yml, toget: "https://github.com/docker/compose/releases/download/1.5.0/docker-compose-Linux-x86_64" }

- name: Install Docker Compose
  sudo: yes
  copy: src="{{ cached }}" dest=/usr/local/bin/docker-compose

- name: Make Docker Machine compose
  sudo: yes
  file: path=/usr/local/bin/docker-compose state=file mode="u+rx,a+x,g+x"
