---

- name: Create kubernetes directory
  file:
    path: "{{ tools.path }}/kubernetes"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory

- { include: get-and-cache.yml, toget: "{{ tools.kubectl.url }}" }

- name: Copy kubectl binary to tools directory
  copy:
    src: "{{ cached }}"
    dest: "{{ tools.path }}/kubernetes/kubectl"
  when: cache_changed

- name: Set +x on kubectl executable
  file:
    path: "{{ tools.path }}/kubernetes/kubectl"
    state: file
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "u+rwx,g+rx"

- { include: get-and-cache.yml, toget: "{{ tools.minikube.url }}" }

- name: Copy minikube binary to tools directory
  copy:
    src: "{{ cached }}"
    dest: "{{ tools.path }}/kubernetes/minikube"
  when: cache_changed

- name: Set +x on minikube executable
  file:
    path: "{{ tools.path }}/kubernetes/minikube"
    state: file
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "u+rwx,g+rx"

- { include: get-and-cache.yml, toget: "{{ tools.kops.url }}" }

- name: Copy kops binary to tools directory
  copy:
    src: "{{ cached }}"
    dest: "{{ tools.path }}/kubernetes/kops"
  when: cache_changed

- name: Set +x on kops executable
  file:
    path: "{{ tools.path }}/kubernetes/kops"
    state: file
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "u+rwx,g+rx"

- name: clone kubectx repository
  become: no
  git:
    repo: "https://github.com/ahmetb/kubectx"
    dest: "{{ user.home }}/tools/kubernetes/kubectx-repo"

- name: Create kubectx symlink
  file:
    src: "{{ user.home }}/tools/kubernetes/kubectx-repo/kubectx"
    dest: "{{ user.home }}/tools/kubernetes/kubectx"
    state: link
    mode: "u+rx,a+x,g+x"

- name: Create kubens symlink
  file:
    src: "{{ user.home }}/tools/kubernetes/kubectx-repo/kubens"
    dest: "{{ user.home }}/tools/kubernetes/kubens"
    state: link
    mode: "u+rx,a+x,g+x"
