HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

export PATH=~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

alias la='ls -lAh'
alias ll='ls -lh'
alias ls='ls --color=tty'
alias l=ls

alias vi="vim"

alias get='sudo apt install'
alias search='sudo apt search'

alias h='history'
alias c='clear'

function _mki() {
	mkdir -p $1 && cd $_
}
alias mki=_mki

alias show-listening-port="sudo netstat -taupn | grep LISTEN"

# fixed windows name for tmux
export DISABLE_AUTO_TITLE=true
alias t='tmux'
alias tls="tmux ls"
alias ta="tmux a -t"
alias tk="tmux kill-session -t"

alias d='docker'
alias dl='docker ps -l -q'
alias dm='docker-machine'
alias dc='docker-compose'
alias dcleanup='docker system prune'

export EDITOR=vim
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gpr='git pull --rebase'
alias gl='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
alias grm='git rebase origin/master'

function httpie_docker() {
	docker run -it --rm --net=host clue/httpie $@
}
alias http=httpie_docker

function resetenv() {
	{{ resetenv_path }}/resetenv $@
	source $HOME/.zshrc
}
alias r=resetenv

export JAVA_HOME=/usr/lib/jvm/java-1.8.0
export PATH=$JAVA_HOME/bin:$PATH

alias v="vagrant"
export PATH={{ tools.path }}/terraform/:$PATH
export PATH={{ tools.path }}/packer/:$PATH
alias p="packer"
export PATH={{ tools.path }}/vault/:$PATH

export PATH={{ tools.path }}/kubernetes/:$PATH
source <(kubectl completion bash)
alias k=kubectl
complete -o default -F __start_kubectl k

alias kctx=kubectx
alias kns=kubens

kx() {
	local selectedPod=$(kubectl get pods --all-namespaces -owide | fzf --tac)
	local namespace=$(awk '{print $1}' <<< $selectedPod)
	local podName=$(awk '{print $2}' <<< $selectedPod)

	local cmd=${@:-"bash"}

	echo kubectl exec -it --namespace $namespace $podName $cmd
	kubectl exec -it --namespace $namespace $podName $cmd
}

kl() {
	local attr=${@:-""}
	local selectedPod=$(kubectl get pods --all-namespaces -owide | fzf --tac)
	local namespace=$(awk '{print $1}' <<< $selectedPod)
	local podName=$(awk '{print $2}' <<< $selectedPod)

	echo kubectl logs -f $attr --namespace $namespace $podName
	kubectl logs -f $attr --namespace $namespace $podName
}

alias f=vifm

alias secpass="openssl rand -base64 24"
alias hexpass="openssl rand -hex 24"

# trailing whitespace at the end is necessary to expand "aliased" arguments
alias watch='watch --color '

source ~/.hub.bash_completions.sh

if [ -f `which powerline-daemon` ]; then
  powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
  source /usr/share/powerline/bindings/bash/powerline.sh
fi

if [[ -f ~/.cloudbees.sh ]]; then
	source ~/.cloudbees.sh
fi

[[ -f ~/.fzf.bash ]] && source ~/.fzf.bash

export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

alias h="hub"
alias b="hub browse"
alias pr="hub pull-request"
