syntax on
autocmd Filetype gitcommit setlocal textwidth=72


python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup
set laststatus=2
set t_Co=128
