ZSH=$HOME/.oh-my-zsh
ZSH_THEME="geoffgarside"

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
autoload -Uz compinit
compinit
COMPLETION_WAITING_DOTS="true"

plugins=(git history-substring-search docker mvn lol)
source $ZSH/oh-my-zsh.sh

export PATH=~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# some git aliases from zsh git plugin are provided, I prefer to customize them entirely
unalias -m "*"

alias ...=../..
alias ....=../../..
alias .....=../../../..
alias ......=../../../../..

alias la='ls -lAh'
alias ll='ls -lh'
alias ls='ls --color=tty'
alias l=ls

alias vi="vimx"

alias get='sudo dnf install'
alias search='sudo dnf search'

alias h='history'
alias c='clear'

function _mki() {
	mkdir -p $1 && cd $_
}
alias mki=_mki

alias show-listening-port="sudo netstat -taupn | grep LISTEN"

# fixed windows name for tmux
export DISABLE_AUTO_TITLE=true
alias t='tmux'
alias tls="tmux ls"
alias ta="tmux a -t"
alias tk="tmux kill-session -t"

source {{ user.home }}/.tmuxinator-completion.zsh

alias d='docker'
alias dl='docker ps -l -q'
alias dm='docker-machine'
alias dc='docker-compose'
alias dcleanup='docker system prune'

export EDITOR=vimx
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gpr='git pull --rebase'
alias gl='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
alias grm='git rebase origin/master'

function httpie_docker() {
	docker run -it --rm --net=host clue/httpie $@
}
alias http=httpie_docker

function resetenv() {
	{{ resetenv_path }}/resetenv $@
	source $HOME/.zshrc
}
alias r=resetenv

export PATH={{ tools.path }}/sublime_text_3:$PATH
alias s='sublime_text'
alias sub='sublime_text'

export JAVA_HOME=/usr/lib/jvm/java-1.8.0
export PATH=$JAVA_HOME/bin:$PATH

alias v="vagrant"
export PATH={{ tools.path }}/terraform/:$PATH
export PATH={{ tools.path }}/packer/:$PATH
alias p="packer"

export PATH={{ tools.path }}/kubernetes/:$PATH
alias k="kubectl"
alias kg='kubectl get'
alias kgpo='kubectl get pods'
alias krm='kubectl delete'
alias krmf='kubectl delete -f'
alias ka='kubectl apply -f'
alias klo='kubectl logs -f'
alias kex='kubectl exec -i -t'

source <(kubectl completion zsh)

# The next line updates PATH for the Google Cloud SDK.
if [ -f '{{ tools.path }}/google-cloud-sdk/path.zsh.inc' ]; then source '{{ tools.path }}/google-cloud-sdk/path.zsh.inc'; fi
# The next line enables shell command completion for gcloud.
if [ -f '{{ tools.path }}/google-cloud-sdk/completion.zsh.inc' ]; then source '{{ tools.path }}/google-cloud-sdk/completion.zsh.inc'; fi

alias f=vifm

alias secpass="openssl rand -base64 24"
alias hexpass="openssl rand -hex 24"

# trailing whitespace at the end is necessary to expand "aliased" arguments
alias watch='watch --color '

export PS1="[$MODE] $PS1"

source /usr/share/powerline/zsh/powerline.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [ -f ~/.myzhrc ]; then
  source ~/.myzhrc
fi
